### ISSUE TITLE
always failing transaction Bitcoin Balance

### ISSUE THREAD

**Issue by chriscrutt** [provable-things/ethereum-examples#80]
**Expected behavior**

On Remix, I am attempting to read the BTC balance of 3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r (which is~ 0.0257) using your BitcoinBalanceExample file

**Actual behavior**

I am run getBalance on Remix I receive

> Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
> gas required exceeds allowance (10000000) or always failing transaction

**To reproduce**

1. copy the [BitcoinBalanceExample.sol](https://github.com/provable-things/ethereum-examples/blob/master/solidity/truffle-examples/bitcoin-balance/contracts/BitcoinAddressExample.sol) file and paste it in Remix.
2. make sure the compiler is set to 0.5.17
3. replace `import "./provableAPI.sol";` with `import "github.com/oraclize/ethereum-api/provableAPI.sol";`
4. **compile** with `Enable optimization` enabled
4. connect MetaMask to Remix on the Rinkeby testnet
5. Deploy the contract
6. Go to newly deployed contract and enter `3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r` for `getBalance`
7. Once you attempt to run the function, you will receive the error message above

**Comment by gskapka** [comment]
Good find and thank you for the bug report. Testing this out via the Truffle example also shows how a balance cannot be retrieved. Tagging this as a bug to be fixed.

**Comment by chriscrutt** [comment]
@gskapka what would be the best way to solve this issue? I can do some troubleshooting if you point me in the right direction

**Comment by gskapka** [comment]
Hi @chriscrutt - thank you for the offer! A lot of the time the first thing to check is whether the zip file containing the computation still exists on IPFS, sometimes it can become unpinned and need reuploading. Once re-uploaded, changing the hash inside the smart-contract will restore working behaviour.

**Comment by gskapka** [comment]
Hi @chriscrutt - just pinging you to let you know that this issue has now been fixed, and the examples updated. Thank you for bringing it to our attention!
